{
 "title": "Alertas",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Propriedade",
    "label": "Propriedade",
    "query": "SELECT DISTINCT id_propriedade AS __value, propriedade AS __text\nFROM vw_medicoes_base\nORDER BY __text;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total de Alertas Últimos 7 dias",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT COUNT(*)\nFROM vw_alertas_base\nWHERE\n    id_propriedade = '$Propriedade'\n    AND data_alerta >= now() - interval '7 days';"
    }
   ]
  },
  {
   "title": "Total de Alertas por Talhão",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT\n    talhao,\n    COUNT(*) AS total_alertas\nFROM vw_alertas_base\nWHERE\n    $__timeFilter(data_alerta)\n    AND id_propriedade = '$Propriedade'\nGROUP BY talhao\nORDER BY total_alertas DESC;"
    }
   ]
  },
  {
   "title": "Evolução de Alertas Propriedade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT\n    date_trunc('hour', data_alerta) AS time,\n    COUNT(*) AS total\nFROM vw_alertas_base\nWHERE\n    $__timeFilter(data_alerta)\n    AND id_propriedade = '$Propriedade'\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Quantidade de Alertas Propriedade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT\n    tipo_descricao,\n    COUNT(*) AS total\nFROM vw_alertas_base\nWHERE\n    $__timeFilter(data_alerta)\n    AND id_propriedade = '$Propriedade'\nGROUP BY tipo_descricao\nORDER BY total DESC;"
    }
   ]
  }
 ]
}