{
 "title": "Status Atual Talhão",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Propriedade",
    "label": "Propriedade",
    "query": "SELECT DISTINCT id_propriedade AS __value, propriedade AS __text\nFROM vw_medicoes_base\nORDER BY __text;"
   },
   {
    "name": "Talhao",
    "label": "Talhão",
    "query": "SELECT DISTINCT id_talhao AS __value, talhao AS __text\nFROM vw_medicoes_base\nWHERE id_propriedade = '$Propriedade'\nORDER BY __text;"
   }
  ]
 },
 "panels": [
  {
   "title": "Chuva Hoje",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT COALESCE(SUM(precipitacao_total), 0)\nFROM vw_precipitacao_diaria\nWHERE\nid_talhao = '$Talhao'\nAND dia = date_trunc('day', now());"
    }
   ]
  },
  {
   "title": "Umidade Atual",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT valor\nFROM vw_medicoes_ultima\nWHERE\ntipo = 1\nAND id_talhao = '$Talhao';"
    }
   ]
  },
  {
   "title": "Temperatura Atual",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashAgro",
     "rawSql": "SELECT valor\nFROM vw_medicoes_ultima\nWHERE\ntipo = 0\nAND id_talhao = '$Talhao';"
    }
   ]
  }
 ]
}